# Simple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('train.csv')
X=dataset[['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']].values
y=dataset[['SalePrice']].values

In [3]:
print(X)

[[   7 1710    2  548  856]
 [   6 1262    2  460 1262]
 [   7 1786    2  608  920]
 ...
 [   7 2340    1  252 1152]
 [   5 1078    1  240 1078]
 [   5 1256    1  276 1256]]


In [4]:
print(y)

[[208500]
 [181500]
 [223500]
 ...
 [266500]
 [142125]
 [147500]]


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
regressor.score(X_test,y_test)

0.7924540848932645

## Predicting the Test set results

In [7]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[255386.4  200624.  ]
 [157476.2  133000.  ]
 [116435.54 110000.  ]
 [231090.57 192000.  ]
 [128239.95  88000.  ]
 [117189.93  85000.  ]
 [260386.62 282922.  ]
 [152482.67 141000.  ]
 [466270.72 745000.  ]
 [172318.51 148800.  ]
 [207539.27 208900.  ]
 [185559.26 136905.  ]
 [223582.72 225000.  ]
 [107188.25 123000.  ]
 [144594.35 119200.  ]
 [138972.93 145000.  ]
 [215087.67 190000.  ]
 [ 71019.34 123600.  ]
 [132274.49 149350.  ]
 [193798.19 155000.  ]
 [152020.9  166000.  ]
 [146042.92 144500.  ]
 [121546.44 110000.  ]
 [167676.98 174000.  ]
 [193779.21 185000.  ]
 [233869.18 168000.  ]
 [174758.06 177500.  ]
 [ 44422.26  84500.  ]
 [300809.18 320000.  ]
 [120542.12 118500.  ]
 [208176.16 110000.  ]
 [206317.93 213000.  ]
 [150781.89 156000.  ]
 [282785.13 250000.  ]
 [303937.78 372500.  ]
 [191514.8  175000.  ]
 [271471.26 277500.  ]
 [125598.29 112500.  ]
 [228208.59 263000.  ]
 [292950.37 325000.  ]
 [215737.95 243000.  ]
 [132534.49 130000.  ]
 [203447.14 164990.  ]
 [288842.45

## Predicting the  model on Test data

In [8]:
import pickle

In [9]:
testdata=pd.read_csv('test.csv')
testdata
testdata = testdata.replace('?',np.NaN)
testdata = testdata.fillna(testdata.median())
testdata

C:\Users\shubh\AppData\Local\Temp\ipykernel_17988\970805088.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  testdata = testdata.fillna(testdata.median())


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [10]:
X1=testdata[['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']].values

In [11]:
print(X1)

[[5.00e+00 8.96e+02 1.00e+00 7.30e+02 8.82e+02]
 [6.00e+00 1.33e+03 1.00e+00 3.12e+02 1.33e+03]
 [5.00e+00 1.63e+03 2.00e+00 4.82e+02 9.28e+02]
 ...
 [5.00e+00 1.22e+03 2.00e+00 5.76e+02 1.22e+03]
 [5.00e+00 9.70e+02 0.00e+00 0.00e+00 9.12e+02]
 [7.00e+00 2.00e+03 3.00e+00 6.50e+02 9.96e+02]]


In [12]:
predictions=regressor.predict(X1)
predictions=pd.DataFrame(predictions).values
predictions

array([[114194.12],
       [163921.95],
       [159524.4 ],
       ...,
       [152589.  ],
       [ 91327.46],
       [243306.41]])

In [13]:
ids=testdata['Id'].values
ids=ids.reshape(-1,1)
ids

array([[1461],
       [1462],
       [1463],
       ...,
       [2917],
       [2918],
       [2919]], dtype=int64)

In [14]:
merged_arr = np.concatenate((ids , predictions),axis=1)
merged_arr

array([[  1461.  , 114194.12],
       [  1462.  , 163921.95],
       [  1463.  , 159524.4 ],
       ...,
       [  2917.  , 152589.  ],
       [  2918.  ,  91327.46],
       [  2919.  , 243306.41]])

In [15]:
testsaleprice=pd.DataFrame(merged_arr)
testsaleprice

0              1
0     1461.0  114194.116654
1     1462.0  163921.950809
2     1463.0  159524.396513
3     1464.0  181776.542697
4     1465.0  226390.372104
...      ...            ...
1454  2915.0   61748.696818
1455  2916.0   82073.983618
1456  2917.0  152589.002631
1457  2918.0   91327.462240
1458  2919.0  243306.408919

[1459 rows x 2 columns]

In [16]:
testsaleprice.columns=['ID','SalePrice']
testsaleprice

ID      SalePrice
0     1461.0  114194.116654
1     1462.0  163921.950809
2     1463.0  159524.396513
3     1464.0  181776.542697
4     1465.0  226390.372104
...      ...            ...
1454  2915.0   61748.696818
1455  2916.0   82073.983618
1456  2917.0  152589.002631
1457  2918.0   91327.462240
1458  2919.0  243306.408919

[1459 rows x 2 columns]